// Generated by npm run content:unsplash. Do not edit by hand.
import type { PortfolioProject, PortfolioSlide } from './portfolio';

export const PORTFOLIO_SLIDES = [
  {
    "alt": "time lapse photography of man riding car",
    "category": "Automotive film",
    "id": "MyjVReZ5GLQ",
    "imageUrl": "https://images.unsplash.com/photo-1485463611174-f302f6a5c1c9?ixid=M3wxMDA0NDc4fDB8MXxzZWFyY2h8MXx8cGVyZm9ybWFuY2UlMjBjYXIlMjBkcml2aW5nJTIwbW90aW9ufGVufDF8MHx8fDE3ODQ4MzI1NjB8MA&ixlib=rb-4.1.0&auto=format&fit=crop&q=86&w=2400",
    "photographerName": "Samuele Errico Piccarini",
    "photographerProfileUrl": "https://unsplash.com/@samuele_piccarini?utm_source=ziron_portfolio&utm_medium=referral",
    "sourceUrl": "https://unsplash.com/photos/time-lapse-photography-of-man-riding-car-MyjVReZ5GLQ?utm_source=ziron_portfolio&utm_medium=referral",
    "title": "Velocity, framed"
  },
  {
    "alt": "a man working on a motorcycle in a garage",
    "category": "Motorcycle stories",
    "id": "4ORysIjH-mY",
    "imageUrl": "https://images.unsplash.com/photo-1636761358757-0a616eb9e17e?ixid=M3wxMDA0NDc4fDB8MXxzZWFyY2h8MXx8bW90b3JjeWNsZSUyMHdvcmtzaG9wJTIwY2luZW1hdGljfGVufDF8MHx8fDE3ODQ3NDkwMTJ8MA&ixlib=rb-4.1.0&auto=format&fit=crop&q=86&w=2400",
    "photographerName": "Angry._.Kat",
    "photographerProfileUrl": "https://unsplash.com/@_ks_?utm_source=ziron_portfolio&utm_medium=referral",
    "sourceUrl": "https://unsplash.com/photos/a-man-working-on-a-motorcycle-in-a-garage-4ORysIjH-mY?utm_source=ziron_portfolio&utm_medium=referral",
    "title": "Built by hand"
  },
  {
    "alt": "close-up photography of black metal gears",
    "category": "Industrial image",
    "id": "hsPFuudRg5I",
    "imageUrl": "https://images.unsplash.com/photo-1524514587686-e2909d726e9b?ixid=M3wxMDA0NDc4fDB8MXxzZWFyY2h8MXx8aW5kdXN0cmlhbCUyMG1hY2hpbmVyeSUyMGNpbmVtYXRpY3xlbnwxfDB8fHwxNzg0NzQ5MDEyfDA&ixlib=rb-4.1.0&auto=format&fit=crop&q=86&w=2400",
    "photographerName": "Isis França",
    "photographerProfileUrl": "https://unsplash.com/@isisfra?utm_source=ziron_portfolio&utm_medium=referral",
    "sourceUrl": "https://unsplash.com/photos/close-up-photography-of-black-metal-gears-hsPFuudRg5I?utm_source=ziron_portfolio&utm_medium=referral",
    "title": "Precision at scale"
  }
] satisfies PortfolioSlide[];

export const FEATURED_PROJECT = {
  "category": "Film produkcyjny / Kampania 2026",
  "images": [
    {
      "alt": "a tractor is parked in the snow at night",
      "height": 1600,
      "id": "UoLKbnqXyy0",
      "imageUrl": "https://images.unsplash.com/photo-1675345313491-8520fc560563?ixid=M3wxMDA0NDc4fDB8MXxzZWFyY2h8MXx8c25vdyUyMHBsb3clMjB0cnVjayUyMG5pZ2h0fGVufDF8MHx8fDE3ODQ4MzI1NTl8MA&ixlib=rb-4.1.0&auto=format&fit=crop&q=86&w=2400",
      "photographerName": "Kajetan Sumila",
      "photographerProfileUrl": "https://unsplash.com/@kajtek?utm_source=ziron_portfolio&utm_medium=referral",
      "sourceUrl": "https://unsplash.com/photos/a-tractor-is-parked-in-the-snow-at-night-UoLKbnqXyy0?utm_source=ziron_portfolio&utm_medium=referral",
      "width": 2400
    },
    {
      "alt": "yellow and black heavy equipment on brown field during daytime",
      "height": 1600,
      "id": "N1LBcqLP9ec",
      "imageUrl": "https://images.unsplash.com/photo-1629807473015-41699c4471b5?ixid=M3wxMDA0NDc4fDB8MXxzZWFyY2h8MXx8aGVhdnklMjBjb25zdHJ1Y3Rpb24lMjBsb2FkZXJ8ZW58MXwwfHx8MTc4NDgzMjU1OXww&ixlib=rb-4.1.0&auto=format&fit=crop&q=86&w=2400",
      "photographerName": "Zac Edmonds",
      "photographerProfileUrl": "https://unsplash.com/@zacedmo?utm_source=ziron_portfolio&utm_medium=referral",
      "sourceUrl": "https://unsplash.com/photos/yellow-and-black-heavy-equipment-on-brown-field-during-daytime-N1LBcqLP9ec?utm_source=ziron_portfolio&utm_medium=referral",
      "width": 2400
    },
    {
      "alt": "Two semi-trucks driving on a highway.",
      "height": 1600,
      "id": "P0bVatS8Jdw",
      "imageUrl": "https://images.unsplash.com/photo-1766785368863-f2188a8c8b32?ixid=M3wxMDA0NDc4fDB8MXxzZWFyY2h8MXx8c2VtaSUyMHRydWNrJTIwcm9hZHxlbnwxfDB8fHwxNzg0ODMyNTU5fDA&ixlib=rb-4.1.0&auto=format&fit=crop&q=86&w=2400",
      "photographerName": "Bhargav Panchal",
      "photographerProfileUrl": "https://unsplash.com/@bhargavpanchal1986?utm_source=ziron_portfolio&utm_medium=referral",
      "sourceUrl": "https://unsplash.com/photos/two-semi-trucks-driving-on-a-highway-P0bVatS8Jdw?utm_source=ziron_portfolio&utm_medium=referral",
      "width": 2400
    },
    {
      "alt": "red sports car",
      "height": 1600,
      "id": "tmAynVA_ihE",
      "imageUrl": "https://images.unsplash.com/photo-1508974239320-0a029497e820?ixid=M3wxMDA0NDc4fDB8MXxzZWFyY2h8MXx8c3BvcnRzJTIwY2FyJTIwZGV0YWlsfGVufDF8MHx8fDE3ODQ4MzI1NTl8MA&ixlib=rb-4.1.0&auto=format&fit=crop&q=86&w=2400",
      "photographerName": "Yuvraj Singh",
      "photographerProfileUrl": "https://unsplash.com/@yxvi?utm_source=ziron_portfolio&utm_medium=referral",
      "sourceUrl": "https://unsplash.com/photos/red-sports-car-tmAynVA_ihE?utm_source=ziron_portfolio&utm_medium=referral",
      "width": 2400
    },
    {
      "alt": "green tractor on brown grass field under blue sky during daytime",
      "height": 1600,
      "id": "dDc0vuVH_LU",
      "imageUrl": "https://images.unsplash.com/photo-1594771804886-a933bb2d609b?ixid=M3wxMDA0NDc4fDB8MXxzZWFyY2h8MXx8dHJhY3RvciUyMGZpZWxkfGVufDF8MHx8fDE3ODQ4MzI1NTl8MA&ixlib=rb-4.1.0&auto=format&fit=crop&q=86&w=2400",
      "photographerName": "Randy Fath",
      "photographerProfileUrl": "https://unsplash.com/@randyfath?utm_source=ziron_portfolio&utm_medium=referral",
      "sourceUrl": "https://unsplash.com/photos/green-tractor-on-brown-grass-field-under-blue-sky-during-daytime-dDc0vuVH_LU?utm_source=ziron_portfolio&utm_medium=referral",
      "width": 2400
    },
    {
      "alt": "black suv on brown sand during daytime",
      "height": 1600,
      "id": "0Fh2wHv_HfU",
      "imageUrl": "https://images.unsplash.com/photo-1627490600102-5c1d45491d57?ixid=M3wxMDA0NDc4fDB8MXxzZWFyY2h8MXx8b2ZmJTIwcm9hZCUyMHBpY2t1cCUyMGR1c3R8ZW58MXwwfHx8MTc4NDgzMjU1OXww&ixlib=rb-4.1.0&auto=format&fit=crop&q=86&w=2400",
      "photographerName": "Chris Cordes",
      "photographerProfileUrl": "https://unsplash.com/@4x4_touring?utm_source=ziron_portfolio&utm_medium=referral",
      "sourceUrl": "https://unsplash.com/photos/black-suv-on-brown-sand-during-daytime-0Fh2wHv_HfU?utm_source=ziron_portfolio&utm_medium=referral",
      "width": 2400
    },
    {
      "alt": "running black Porsche sedan",
      "height": 1600,
      "id": "3ZUsNJhi_Ik",
      "imageUrl": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?ixid=M3wxMDA0NDc4fDB8MXxzZWFyY2h8MXx8bHV4dXJ5JTIwc3BvcnRzJTIwY2FyJTIwcm9hZHxlbnwxfDB8fHwxNzg0ODMyNTU5fDA&ixlib=rb-4.1.0&auto=format&fit=crop&q=86&w=2400",
      "photographerName": "Campbell",
      "photographerProfileUrl": "https://unsplash.com/@campful?utm_source=ziron_portfolio&utm_medium=referral",
      "sourceUrl": "https://unsplash.com/photos/running-black-porsche-sedan-3ZUsNJhi_Ik?utm_source=ziron_portfolio&utm_medium=referral",
      "width": 2400
    },
    {
      "alt": "a tractor with a plow in the snow",
      "height": 1600,
      "id": "6MYkr822DvY",
      "imageUrl": "https://images.unsplash.com/photo-1679309906730-2c869a841020?ixid=M3wxMDA0NDc4fDB8MXxzZWFyY2h8MXx8YWdyaWN1bHR1cmUlMjB0cmFjdG9yJTIwc25vd3xlbnwxfDB8fHwxNzg0ODMyNTU5fDA&ixlib=rb-4.1.0&auto=format&fit=crop&q=86&w=2400",
      "photographerName": "Photos of Korea",
      "photographerProfileUrl": "https://unsplash.com/@photosofkorea?utm_source=ziron_portfolio&utm_medium=referral",
      "sourceUrl": "https://unsplash.com/photos/a-tractor-with-a-plow-in-the-snow-6MYkr822DvY?utm_source=ziron_portfolio&utm_medium=referral",
      "width": 2400
    }
  ],
  "summary": "Maszyny nie pozują. Pracują. Pokazaliśmy ich siłę tam, gdzie jest najbardziej prawdziwa — w pyle, śniegu, deszczu i pełnym tempie.",
  "title": "Siła w ruchu"
} satisfies PortfolioProject;
