// Generated by npm run content:unsplash. Do not edit by hand.
import type { PortfolioSlide } from './portfolio';

export const PORTFOLIO_SLIDES = [
  {
    "alt": "time lapse photography of man riding car",
    "category": "Automotive film",
    "id": "MyjVReZ5GLQ",
    "imageUrl": "https://images.unsplash.com/photo-1485463611174-f302f6a5c1c9?ixid=M3wxMDA0NDc4fDB8MXxzZWFyY2h8MXx8cGVyZm9ybWFuY2UlMjBjYXIlMjBkcml2aW5nJTIwbW90aW9ufGVufDF8MHx8fDE3ODQ3NDkwMTJ8MA&ixlib=rb-4.1.0&auto=format&fit=crop&q=86&w=2400",
    "photographerName": "Samuele Errico Piccarini",
    "photographerProfileUrl": "https://unsplash.com/@samuele_piccarini?utm_source=ziron_portfolio&utm_medium=referral",
    "sourceUrl": "https://unsplash.com/photos/time-lapse-photography-of-man-riding-car-MyjVReZ5GLQ?utm_source=ziron_portfolio&utm_medium=referral",
    "title": "Velocity, framed"
  },
  {
    "alt": "a man working on a motorcycle in a garage",
    "category": "Motorcycle stories",
    "id": "4ORysIjH-mY",
    "imageUrl": "https://images.unsplash.com/photo-1636761358757-0a616eb9e17e?ixid=M3wxMDA0NDc4fDB8MXxzZWFyY2h8MXx8bW90b3JjeWNsZSUyMHdvcmtzaG9wJTIwY2luZW1hdGljfGVufDF8MHx8fDE3ODQ3NDkwMTJ8MA&ixlib=rb-4.1.0&auto=format&fit=crop&q=86&w=2400",
    "photographerName": "Angry._.Kat",
    "photographerProfileUrl": "https://unsplash.com/@_ks_?utm_source=ziron_portfolio&utm_medium=referral",
    "sourceUrl": "https://unsplash.com/photos/a-man-working-on-a-motorcycle-in-a-garage-4ORysIjH-mY?utm_source=ziron_portfolio&utm_medium=referral",
    "title": "Built by hand"
  },
  {
    "alt": "close-up photography of black metal gears",
    "category": "Industrial image",
    "id": "hsPFuudRg5I",
    "imageUrl": "https://images.unsplash.com/photo-1524514587686-e2909d726e9b?ixid=M3wxMDA0NDc4fDB8MXxzZWFyY2h8MXx8aW5kdXN0cmlhbCUyMG1hY2hpbmVyeSUyMGNpbmVtYXRpY3xlbnwxfDB8fHwxNzg0NzQ5MDEyfDA&ixlib=rb-4.1.0&auto=format&fit=crop&q=86&w=2400",
    "photographerName": "Isis França",
    "photographerProfileUrl": "https://unsplash.com/@isisfra?utm_source=ziron_portfolio&utm_medium=referral",
    "sourceUrl": "https://unsplash.com/photos/close-up-photography-of-black-metal-gears-hsPFuudRg5I?utm_source=ziron_portfolio&utm_medium=referral",
    "title": "Precision at scale"
  }
] satisfies PortfolioSlide[];
